import { HistoricalEra, LanguageOption, Translation } from './types';

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'pt', name: 'Português' },
  { code: 'ru', name: 'Русский' },
  { code: 'ar', name: 'العربية' },
  { code: 'zh', name: '中文' },
  { code: 'ja', name: '日本語' },
  { code: 'ko', name: '한국어' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'sw', name: 'Kiswahili' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'rw', name: 'Kinyarwanda' },
];

export const UI_TEXT: { [key: string]: Translation } = {
  mainTitle: {
    en: "Chronos",
    fr: "Chronos",
    rw: "Chronos",
    sw: "Chronos",
    es: "Chronos",
    ar: "كرونوس",
    zh: "克罗诺斯",
    hi: "क्रोनोस",
    pt: "Chronos",
    bn: "ক্রোনোস",
    ru: "Хронос",
    ja: "クロノス",
    de: "Chronos",
    ko: "크로노스",
    tr: "Chronos",
    it: "Chronos",
    id: "Chronos"
  },
  welcomeMessage: {
    en: "An Interactive History of the World",
    fr: "Une Histoire Interactive du Monde",
    rw: "Amateka y'Isi Yose",
    sw: "Historia ya Ulimwengu inayoingiliana",
    es: "Una Historia Interactiva del Mundo",
    ar: "تاريخ تفاعلي للعالم",
    zh: "世界互动历史",
    hi: "विश्व का एक इंटरैक्टिव इतिहास",
    pt: "Uma História Interativa do Mundo",
    bn: "বিশ্বের একটি ইন্টারেক্টিভ ইতিহাস",
    ru: "Интерактивная история мира",
    ja: "世界のインタラクティブな歴史",
    de: "Eine interaktive Geschichte der Welt",
    ko: "세계의 대화형 역사",
    tr: "Dünyanın Etkileşimli bir Tarihi",
    it: "Una Storia Interattiva del Mondo",
    id: "Sejarah Interaktif Dunia"
  },
  startChat: {
    en: "Ask our AI Historian",
    fr: "Demandez à notre historien IA",
    rw: "Baza Umuhanga wacu mu by'Amateka wa AI",
    sw: "Uliza Mwanahistoria wetu wa AI",
    es: "Pregúntale a nuestro historiador de IA",
    ar: "اسأل مؤرخنا الذكي",
    zh: "询问我们的AI历史学家",
    hi: "हमारे एआई इतिहासकार से पूछें",
    pt: "Pergunte ao nosso Historiador de IA",
    bn: "আমাদের এআই ইতিহাসবিদকে জিজ্ঞাসা করুন",
    ru: "Спросите нашего ИИ-историка",
    ja: "AI歴史家に質問する",
    de: "Fragen Sie unseren KI-Historiker",
    ko: "AI 역사학자에게 물어보세요",
    tr: "Yapay Zeka Tarihçimize Sorun",
    it: "Chiedi al nostro Storico AI",
    id: "Tanya Sejarawan AI kami"
  },
  aiHistorianTitle: {
    en: "AI Historian",
    fr: "Historien IA",
    rw: "Umuhanga mu by'Amateka wa AI",
    sw: "Mwanahistoria wa AI",
    es: "Historiador de IA",
    ar: "مؤرخ الذكاء الاصطناعي",
    zh: "AI历史学家",
    hi: "एआई इतिहासकार",
    pt: "Historiador de IA",
    bn: "এআই ইতিহাসবিদ",
    ru: "ИИ-историк",
    ja: "AI歴史家",
    de: "KI-Historiker",
    ko: "AI 역사학자",
    tr: "Yapay Zeka Tarihçisi",
    it: "Storico AI",
    id: "Sejarawan AI"
  },
  chatPlaceholder: {
    en: "Ask about any event or figure in history...",
    fr: "Posez des questions sur n'importe quel événement ou personnage de l'histoire...",
    rw: "Baza ikibazo kijyanye n'icyabaye cyangwa umuntu mu mateka...",
    sw: "Uliza kuhusu tukio lolote au mtu yeyote katika historia...",
    es: "Pregunta sobre cualquier evento o figura de la historia...",
    ar: "اسأل عن أي حدث أو شخصية في التاريخ ...",
    zh: "询问历史上的任何事件或人物...",
    hi: "इतिहास में किसी भी घटना या व्यक्ति के बारे में पूछें...",
    pt: "Pergunte sobre qualquer evento ou figura da história...",
    bn: "ইতিহাসের যেকোনো ঘটনা বা ব্যক্তিত্ব সম্পর্কে জিজ্ঞাসা করুন...",
    ru: "Спросите о любом событии или личности в истории...",
    ja: "歴史上の出来事や人物について質問してください...",
    de: "Fragen Sie nach einem Ereignis oder einer Persönlichkeit in der Geschichte...",
    ko: "역사 속의 사건이나 인물에 대해 물어보세요...",
    tr: "Tarihteki herhangi bir olay veya kişi hakkında soru sorun...",
    it: "Chiedi informazioni su qualsiasi evento o personaggio della storia...",
    id: "Tanyakan tentang peristiwa atau tokoh apa pun dalam sejarah..."
  },
  backToEras: {
      en: "Back to Eras",
      fr: "Retour aux Époques",
      rw: "Subira ku Bihe",
      sw: "Rudi kwenye Enzi",
      es: "Volver a las Eras",
      ar: "العودة إلى العصور",
      zh: "返回时代",
      hi: "युगों पर वापस",
      pt: "Voltar para as Eras",
      bn: "যুগে ফিরে যান",
      ru: "Назад к эпохам",
      ja: "時代に戻る",
      de: "Zurück zu den Epochen",
      ko: "시대로 돌아가기",
      tr: "Çağlara Geri Dön",
      it: "Torna alle Ere",
      id: "Kembali ke Era"
  },
};

export const HISTORICAL_ERAS: HistoricalEra[] = [
    {
        id: "prehistory",
        title: { en: "Prehistory", fr: "Préhistoire", rw: "Amateka ya kera", sw: "Historia ya Awali", es: "Prehistoria", ar: "ما قبل التاريخ", zh: "史前史", hi: "प्रागितिहास", pt: "Pré-história", bn: "প্রাগৈতিহাসিক", ru: "Доисторический период", ja: "先史時代", de: "Vorgeschichte", ko: "선사 시대", tr: "Tarih Öncesi", it: "Preistoria", id: "Prasejarah" },
        period: { en: "c. 2.5M BCE – 1200 BCE", fr: "c. 2,5M AÈC – 1200 AÈC", rw: "c. 2.5M Mbere ya Yezu – 1200 Mbere ya Yezu", sw: "c. 2.5M KK – 1200 KK", es: "c. 2.5M a.C. – 1200 a.C.", ar: "حوالي 2.5 مليون ق.م - 1200 ق.م", zh: "约公元前250万年-公元前1200年", hi: "लगभग 25 लाख ईसा पूर्व - 1200 ईसा पूर्व", pt: "c. 2,5M a.C. – 1200 a.C.", bn: "আনুমানিক ২.৫ মিলিয়ন খ্রিস্টপূর্ব - ১২০০ খ্রিস্টপূর্ব", ru: "ок. 2,5 млн до н.э. – 1200 до н.э.", ja: "紀元前約250万年～紀元前1200年", de: "ca. 2,5 Mio. v. Chr. – 1200 v. Chr.", ko: "기원전 약 250만 년 – 기원전 1200년", tr: "yak. MÖ 2,5M – MÖ 1200", it: "c. 2,5M a.C. – 1200 a.C.", id: "sekitar 2,5 juta SM – 1200 SM" },
        description: { en: "The period of human history before written records, encompassing the Stone Age, Bronze Age, and Iron Age.", fr: "La période de l'histoire humaine avant les documents écrits, englobant l'âge de pierre, l'âge du bronze et l'âge du fer.", rw: "Igihe cy'amateka y'abantu mbere y'inyandiko, gikubiyemo Igihe cy'Amabuye, Igihe cy'Umuringa, n'Igihe cy'Icyuma.", sw: "Kipindi cha historia ya binadamu kabla ya kumbukumbu zilizoandikwa, kinachojumuisha Enzi ya Mawe, Enzi ya Shaba, na Enzi ya Chuma.", es: "El período de la historia humana anterior a los registros escritos, que abarca la Edad de Piedra, la Edad del Bronce y la Edad del Hierro.", ar: "فترة التاريخ البشري قبل السجلات المكتوبة ، وتشمل العصر الحجري والعصر البرونزي والعصر الحديدي.", zh: "人类有文字记录之前的历史时期，包括石器时代、青铜时代和铁器时代。", hi: "लिखित अभिलेखों से पहले मानव इतिहास की अवधि, जिसमें पाषाण युग, कांस्य युग और लौह युग शामिल हैं।", pt: "O período da história humana antes dos registros escritos, abrangendo a Idade da Pedra, a Idade do Bronze e a Idade do Ferro.", bn: "লিখিত রেকর্ডের আগে মানব ইতিহাসের সময়কাল, যা প্রস্তর যুগ, ব্রোঞ্জ যুগ এবং লৌহ যুগকে অন্তর্ভুক্ত করে।", ru: "Период истории человечества до появления письменных источников, охватывающий каменный, бронзовый и железный века.", ja: "文字記録以前の人類の歴史の時代で、石器時代、青銅器時代、鉄器時代を含みます。", de: "Die Periode der Menschheitsgeschichte vor schriftlichen Aufzeichnungen, die die Steinzeit, Bronzezeit und Eisenzeit umfasst.", ko: "문자 기록 이전의 인류 역사 시대로, 석기 시대, 청동기 시대, 철기 시대를 포함합니다.", tr: "Yazılı kayıtlardan önceki insanlık tarihi dönemi, Taş Devri, Tunç Devri ve Demir Devri'ni kapsar.", it: "Il periodo della storia umana prima delle testimonianze scritte, che comprende l'età della pietra, l'età del bronzo e l'età del ferro.", id: "Periode sejarah manusia sebelum catatan tertulis, meliputi Zaman Batu, Zaman Perunggu, dan Zaman Besi." },
        image: "https://images.unsplash.com/photo-1542161324-1deb726986a4?q=80&w=800&auto=format&fit=crop"
    },
    {
        id: "classical",
        title: { en: "Classical Antiquity", fr: "Antiquité classique", rw: "Igihe cya Kera cya Gikirisitu", sw: "Zama za Kale", es: "Antigüedad Clásica", ar: "العصور الكلاسيكية القديمة", zh: "古典时代", hi: "शास्त्रीय पुरातनता", pt: "Antiguidade Clássica", bn: "ধ্রুপদী প্রাচীনত্ব", ru: "Классическая античность", ja: "古典古代", de: "Klassische Antike", ko: "고전 고대", tr: "Klasik Antik Çağ", it: "Antichità classica", id: "Zaman Klasik" },
        period: { en: "8th century BCE – 6th century CE", fr: "VIIIe siècle AÈC – VIe siècle EC", rw: "Ikinyejana cya 8 Mbere ya Yezu – Ikinyejana cya 6 Nyuma ya Yezu", sw: "Karne ya 8 KK – Karne ya 6 BK", es: "Siglo VIII a.C. – Siglo VI d.C.", ar: "القرن الثامن قبل الميلاد - القرن السادس الميلادي", zh: "公元前8世纪-公元6世纪", hi: "8वीं शताब्दी ईसा पूर्व - 6वीं शताब्दी ईस्वी", pt: "Século VIII a.C. – Século VI d.C.", bn: "খ্রিস্টপূর্ব ৮ম শতাব্দী - খ্রিস্টীয় ৬ষ্ঠ শতাব্দী", ru: "VIII век до н.э. – VI век н.э.", ja: "紀元前8世紀～6世紀", de: "8. Jahrhundert v. Chr. – 6. Jahrhundert n. Chr.", ko: "기원전 8세기 – 서기 6세기", tr: "MÖ 8. yüzyıl – MS 6. yüzyıl", it: "VIII secolo a.C. – VI secolo d.C.", id: "Abad ke-8 SM – Abad ke-6 M" },
        description: { en: "The era of Ancient Greece and Ancient Rome, a period of great cultural, philosophical, and political achievements that formed the foundation of Western civilization.", fr: "L'ère de la Grèce antique et de la Rome antique, une période de grandes réalisations culturelles, philosophiques et politiques qui ont jeté les bases de la civilisation occidentale.", rw: "Igihe cy'Ubugiriki bwa Kera n'Uburomani bwa Kera, igihe cy'ibikorwa bikomeye mu muco, filozofiya, na politiki byabaye ishingiro ry'umuco w'i Burengerazuba.", sw: "Enzi ya Ugiriki ya Kale na Roma ya Kale, kipindi cha mafanikio makubwa ya kitamaduni, falsafa, na kisiasa yaliyoanzisha msingi wa ustaarabu wa Magharibi.", es: "La era de la Antigua Grecia y la Antigua Roma, un período de grandes logros culturales, filosóficos y políticos que sentaron las bases de la civilización occidental.", ar: "عصر اليونان القديمة وروما القديمة ، فترة من الإنجازات الثقافية والفلسفية والسياسية العظيمة التي شكلت أساس الحضارة الغربية.", zh: "古希腊和古罗马的时代，这一时期在文化、哲学和政治上取得了巨大成就，奠定了西方文明的基础。", hi: "प्राचीन ग्रीस और प्राचीन रोम का युग, महान सांस्कृतिक, दार्शनिक और राजनीतिक उपलब्धियों का काल जिसने पश्चिमी सभ्यता की नींव रखी।", pt: "A era da Grécia Antiga e da Roma Antiga, um período de grandes realizações culturais, filosóficas e políticas que formaram a base da civilização ocidental.", bn: "প্রাচীন গ্রীস এবং প্রাচীন রোমের যুগ, যা মহান সাংস্কৃতিক, দার্শনিক এবং রাজনৈতিক কৃতিত্বের একটি সময় ছিল এবং পশ্চিমা সভ্যতার ভিত্তি তৈরি করেছিল।", ru: "Эпоха Древней Греции и Древнего Рима, период великих культурных, философских и политических достижений, которые легли в основу западной цивилизации.", ja: "古代ギリシャと古代ローマの時代。西洋文明の基礎を築いた偉大な文化的、哲学的、政治的功績の時代。", de: "Die Ära des antiken Griechenlands und des antiken Roms, eine Zeit großer kultureller, philosophischer und politischer Errungenschaften, die das Fundament der westlichen Zivilisation bildeten.", ko: "고대 그리스와 고대 로마의 시대로, 서양 문명의 기초를 형성한 위대한 문화적, 철학적, 정치적 업적의 시기입니다.", tr: "Batı medeniyetinin temelini oluşturan büyük kültürel, felsefi ve politik başarıların yaşandığı Antik Yunan ve Antik Roma dönemi.", it: "L'era dell'antica Grecia e dell'antica Roma, un periodo di grandi conquiste culturali, filosofiche e politiche che hanno costituito il fondamento della civiltà occidentale.", id: "Era Yunani Kuno dan Roma Kuno, periode pencapaian budaya, filosofis, dan politik besar yang membentuk dasar peradaban Barat." },
        image: "https://images.unsplash.com/photo-1598214886806-2d84a3694f18?q=80&w=800&auto=format&fit=crop"
    },
    {
        id: "middle-ages",
        title: { en: "Middle Ages", fr: "Moyen Âge", rw: "Igihe Hagati", sw: "Zama za Kati", es: "Edad Media", ar: "العصور الوسطى", zh: "中世纪", hi: "मध्य युग", pt: "Idade Média", bn: "মধ্যযুগ", ru: "Средние века", ja: "中世", de: "Mittelalter", ko: "중세", tr: "Orta Çağ", it: "Medioevo", id: "Abad Pertengahan" },
        period: { en: "5th – 15th century CE", fr: "Ve – XVe siècle EC", rw: "Ikinyejana cya 5 – Ikinyejana cya 15 Nyuma ya Yezu", sw: "Karne ya 5 – Karne ya 15 BK", es: "Siglo V – Siglo XV d.C.", ar: "القرن الخامس - القرن الخامس عشر الميلادي", zh: "公元5世纪-15世纪", hi: "5वीं - 15वीं शताब्दी ईस्वी", pt: "Século V – Século XV d.C.", bn: "৫ম - ১৫শ শতাব্দী", ru: "V – XV век н.э.", ja: "5世紀～15世紀", de: "5. – 15. Jahrhundert n. Chr.", ko: "5세기 – 15세기", tr: "5. – 15. yüzyıl", it: "V – XV secolo d.C.", id: "Abad ke-5 – ke-15 M" },
        description: { en: "Spanning from the fall of the Western Roman Empire to the beginning of the Renaissance, this period saw the rise of feudalism, the Byzantine Empire, and the Islamic Golden Age.", fr: "S'étendant de la chute de l'Empire romain d'Occident au début de la Renaissance, cette période a vu la montée du féodalisme, de l'Empire byzantin et de l'âge d'or islamique.", rw: "Kuva ku kugwa kw'Ingoma y'Uburomani bw'i Burengerazuba kugeza ku ntangiriro y'Ubuhinduzi, iki gihe cyabonye izamuka rya feodalizime, Ingoma ya Vizanti, n'Igihe cy'Izahabu cya Isilamu.", sw: "Kuanzia kuanguka kwa Dola la Roma la Magharibi hadi mwanzo wa Renaissance, kipindi hiki kilishuhudia kuongezeka kwa ukabaila, Dola ya Byzantine, na Enzi ya Dhahabu ya Kiislamu.", es: "Abarcando desde la caída del Imperio Romano de Occidente hasta el comienzo del Renacimiento, este período vio el surgimiento del feudalismo, el Imperio Bizantino y la Edad de Oro islámica.", ar: "تمتد من سقوط الإمبراطورية الرومانية الغربية إلى بداية عصر النهضة ، وشهدت هذه الفترة صعود الإقطاع والإمبراطورية البيزنطية والعصر الذهبي للإسلام.", zh: "从西罗马帝国灭亡到文艺复兴开始，这一时期见证了封建主义、拜占庭帝国和伊斯兰黄金时代的兴起。", hi: "पश्चिमी रोमन साम्राज्य के पतन से लेकर पुनर्जागरण की शुरुआत तक फैला यह काल सामंतवाद, बीजान्टिन साम्राज्य और इस्लामी स्वर्ण युग का उदय देखता है।", pt: "Estendendo-se da queda do Império Romano Ocidental ao início do Renascimento, este período viu a ascensão do feudalismo, do Império Bizantino e da Idade de Ouro Islâmica.", bn: "পশ্চিম রোমান সাম্রাজ্যের পতন থেকে রেনেসাঁর শুরু পর্যন্ত বিস্তৃত এই সময়ে সামন্তবাদ, বাইজেন্টাইন সাম্রাজ্য এবং ইসলামী স্বর্ণযুগের উত্থান ঘটে।", ru: "Охватывая период от падения Западной Римской империи до начала эпохи Возрождения, этот период стал свидетелем подъема феодализма, Византийской империи и Золотого века ислама.", ja: "西ローマ帝国の崩壊からルネサンスの始まりまで続くこの時代には、封建主義、ビザンツ帝国、イスラム黄金時代が台頭しました。", de: "Von dem Fall des Weströmischen Reiches bis zum Beginn der Renaissance sah diese Periode den Aufstieg des Feudalismus, des Byzantinischen Reiches und des Goldenen Zeitalters des Islam.", ko: "서로마 제국의 멸망부터 르네상스의 시작까지 이어지는 이 시기는 봉건제, 비잔틴 제국, 이슬람 황금기의 부상을 목격했습니다.", tr: "Batı Roma İmparatorluğu'nun çöküşünden Rönesans'ın başlangıcına kadar uzanan bu dönemde feodalizmin, Bizans İmparatorluğu'nun ve İslam'ın Altın Çağı'nın yükselişine tanık olundu.", it: "Estendendosi dalla caduta dell'Impero Romano d'Occidente all'inizio del Rinascimento, questo periodo vide l'ascesa del feudalesimo, dell'Impero Bizantino e dell'Età dell'Oro islamica.", id: "Membentang dari jatuhnya Kekaisaran Romawi Barat hingga awal Renaisans, periode ini menyaksikan kebangkitan feodalisme, Kekaisaran Bizantium, dan Zaman Keemasan Islam." },
        image: "https://images.unsplash.com/photo-1509619181713-56a228307584?q=80&w=800&auto=format&fit=crop"
    },
    {
        id: "modern",
        title: { en: "Modern Era", fr: "Époque moderne", rw: "Igihe cya Vuba", sw: "Enzi ya Kisasa", es: "Era Moderna", ar: "العصر الحديث", zh: "近代", hi: "आधुनिक युग", pt: "Era Moderna", bn: "আধুনিক যুগ", ru: "Новое время", ja: "近代", de: "Neuzeit", ko: "현대", tr: "Modern Çağ", it: "Era moderna", id: "Era Modern" },
        period: { en: "15th century – present", fr: "XVe siècle – présent", rw: "Ikinyejana cya 15 – kugeza ubu", sw: "Karne ya 15 – sasa", es: "Siglo XV – presente", ar: "القرن الخامس عشر - حتى الآن", zh: "15世纪至今", hi: "15वीं शताब्दी - वर्तमान", pt: "Século XV – presente", bn: "১৫শ শতাব্দী - বর্তমান", ru: "XV век – настоящее время", ja: "15世紀～現在", de: "15. Jahrhundert – heute", ko: "15세기 – 현재", tr: "15. yüzyıl – günümüz", it: "XV secolo – presente", id: "Abad ke-15 – sekarang" },
        description: { en: "Characterized by the Age of Discovery, the Renaissance, the Industrial Revolution, and the Information Age, leading to the interconnected global society of today.", fr: "Caractérisée par l'ère des Grandes Découvertes, la Renaissance, la Révolution industrielle et l'ère de l'information, menant à la société mondiale interconnectée d'aujourd'hui.", rw: "Yaranzwe n'Igihe cy'Ubushakashatsi, Ubuhinduzi, Impinduramatwara mu Inganda, n'Igihe cy'Ikoranabuhanga, biganisha ku muryango w'isi yose uhujwe nk'uyu munsi.", sw: "Inajulikana na Enzi ya Uvumbuzi, Renaissance, Mapinduzi ya Viwanda, na Enzi ya Habari, na kusababisha jamii ya kimataifa iliyounganishwa ya leo.", es: "Caracterizada por la Era de los Descubrimientos, el Renacimiento, la Revolución Industrial y la Era de la Información, que condujo a la sociedad global interconectada de hoy.", ar: "يتميز بعصر الاستكشاف وعصر النهضة والثورة الصناعية وعصر المعلومات ، مما أدى إلى المجتمع العالمي المترابط اليوم.", zh: "以大发现时代、文艺复兴、工业革命和信息时代为特征，导致了今天相互联系的全球社会。", hi: "खोज के युग, पुनर्जागरण, औद्योगिक क्रांति और सूचना युग की विशेषता, जो आज के परस्पर जुड़े वैश्विक समाज की ओर ले जाती है।", pt: "Caracterizada pela Era dos Descobrimentos, o Renascimento, a Revolução Industrial e a Era da Informação, levando à sociedade global interconectada de hoje.", bn: "আবিষ্কারের যুগ, রেনেসাঁ, শিল্প বিপ্লব এবং তথ্য যুগ দ্বারা চিহ্নিত, যা আজকের আন্তঃসংযুক্ত বিশ্ব সমাজের দিকে পরিচালিত করে।", ru: "Характеризуется эпохой Великих географических открытий, Ренессансом, промышленной революцией и информационной эрой, что привело к современному взаимосвязанному глобальному обществу.", ja: "大航海時代、ルネサンス、産業革命、情報化時代を特徴とし、今日の相互接続されたグローバル社会へとつながります。", de: "Gekennzeichnet durch das Zeitalter der Entdeckungen, die Renaissance, die Industrielle Revolution und das Informationszeitalter, die zur vernetzten globalen Gesellschaft von heute führen.", ko: "대항해 시대, 르네상스, 산업 혁명, 정보화 시대로 특징지어지며, 오늘날의 상호 연결된 글로벌 사회로 이어집니다.", tr: "Keşifler Çağı, Rönesans, Sanayi Devrimi ve Bilgi Çağı ile karakterize edilen bu dönem, günümüzün birbirine bağlı küresel toplumuna yol açmıştır.", it: "Caratterizzata dall'età delle scoperte, dal Rinascimento, dalla rivoluzione industriale e dall'era dell'informazione, che hanno portato alla società globale interconnessa di oggi.", id: "Dicirikan oleh Zaman Penjelajahan, Renaisans, Revolusi Industri, dan Zaman Informasi, yang mengarah pada masyarakat global yang saling terhubung saat ini." },
        image: "https://images.unsplash.com/photo-1518932646793-277578503b87?q=80&w=800&auto=format&fit=crop"
    }
];